#!/bin/bash

if [ -n "$TMUX" ]; then
  echo "Скрипт уже запущен внутри сессии tmux. Пожалуйста, запустите этот скрипт вне сессии tmux."
  exit 1
fi

prefix=$1

# Удаляем старую сессию, если она существует
tmux kill-session -t ${prefix}_multi_session 2>/dev/null

# Создание новой сессии без привязки к окну
tmux new-session -d -s ${prefix}_multi_session

# Задаем подключение к серверам
servers=("fns-fw-01" "fns-fw-02" "fns-fw-03" "fns-fw-04" "fns-fw-05" "fns-fw-06" "fns-fw-07" "fns-fw-08" "fns-fw-09" "fns-fw-10" "fns-fw-11" "fns-fw-12")
for i in ${!servers[@]}; do
  server="user@${servers[$i]}"
  tmux send-keys -t ${prefix}_multi_session.$i "ssh $server" Enter
  if ((i<11)); then
    tmux split-window -v -t ${prefix}_multi_session
    tmux select-layout -t ${prefix}_multi_session tiled
  fi
done

# Включаем синхронизацию между панелями
tmux setw -g  synchronize-panes on

# Привязка к сессии.
tmux attach-session -t ${prefix}_multi_session